version: '3.7'

services:

  cserv1: &cserv
    hostname: cserv1
    image: consul:1.15.3
    command: >
      agent
      -server
      -bootstrap-expect 3
      -retry-join cserv1
      -retry-join cserv2
      -retry-join cserv3
    deploy:
      resources:
        limits:
          cpus: 0.5
          memory: 512M

  cserv2:
    <<: *cserv
    hostname: cserv2

  cserv3:
    <<: *cserv
    hostname: cserv3

  nginx:
    build:
      context: .
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: 0.5
          memory: 512M
