# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "debian/bullseye64"

  config.vm.provider :libvirt do |domain|
    domain.cpus = 1
    domain.memory = 1024
  end

  # Tarantool Cartridge Admin UI Port
  config.vm.network "forwarded_port", guest: 8081, host: 8081

  config.vm.provision :ansible do |ansible|
    ansible.config_file = "../ansible/ansible.cfg"
    #ansible.verbose = "vv"
    ansible.playbook = "playbook.yml"
    ansible.become = true
  end

end
