# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "debian/bullseye64"
  config.vm.hostname = "otus-lesson09"

  config.vm.provider :libvirt do |domain|
    domain.cpus = 2
    domain.memory = 2048
  end

  config.vm.provision :ansible do |ansible|
    ansible.config_file = "../ansible/ansible.cfg"
    #ansible.verbose = "vv"
    ansible.playbook = "playbook.yml"
    ansible.become = true
  end

end
